# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: elliotxx
    name: go-cli-action-prototype
  draft: true
  prerelease: auto
  discussion_category_name: General
  header: |
    ## Major changes
    - Item 1
    - Item 2
  footer: |
    ## Thanks!
