name: 'go cli action'
description: 'A github action based on docker and go-cli-prototype'
inputs:
  version:  
    description: 'Show version info'
    required: false
    default: 'false'
  echo:  
    description: 'Show echo info'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.echo}}
