on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to run action
    steps:
      - name: Run action
        id: action
        uses: elliotxx/go-cli-action-prototype@main
        with:
          version: 'true'